### ISSUE TITLE
ValueError: dictionary update sequence element #1 has length 1; 2 is required

### ISSUE THREAD

**Issue by Jimbles** [INCF/BIDS2ISATab#17]
Hey,
I am getting an error with and without the --keep-unknown flag. I think it might have something to do with some of the modalities being a bit unusual - they came from a clinical dataset. 

```
$ bids2isatab Stroke_EIT_Dataset/Anonymised_Radiology/ Stroke_EIT_BIDS -v --keep-unknown
INFO: no files match MRI modality 'T1w', skipping
INFO: no files match MRI modality 'T2w', skipping
INFO: no files match MRI modality 'T1map', skipping
INFO: no files match MRI modality 'T2map', skipping
Traceback (most recent call last):
  File "C:\Python27\Scripts\bids2isatab-script.py", line 11, in <module>
    load_entry_point('BIDS2ISATab==0.1.0', 'console_scripts', 'bids2isatab')()
  File "c:\python27\lib\site-packages\bids2isatab\main.py", line 691, in main
    args.repository_info
  File "c:\python27\lib\site-packages\bids2isatab\main.py", line 579, in extract
    mri_assay_df, mri_par_names = _get_mri_assay_df(bids_directory, modality)
  File "c:\python27\lib\site-packages\bids2isatab\main.py", line 338, in _get_mri_assay_df
    _describe_mri_file)
  File "c:\python27\lib\site-packages\bids2isatab\main.py", line 348, in _get_assay_df
    finfo = file_descr(fname, bids_directory)
  File "c:\python27\lib\site-packages\bids2isatab\main.py", line 273, in _describe_mri_file
    info = _describe_file(fpath, bids_directory)
  File "c:\python27\lib\site-packages\bids2isatab\main.py", line 256, in _describe_file
    comp_dict = dict([c.split('-') for c in fname_components[:-1]])
ValueError: dictionary update sequence element #1 has length 1; 2 is required
```

Any help you could offer would be great!

Jimbles

**Comment by zollilein** [comment]
ich habe dieses Problem jetzt auch....wurde die Lösung schon einmal geschrieben?
